import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Processes the input files generated by GenerateInfoFiles.
 *
 * <p>The program reads the salesmen, products and sales files,
 * calculates the total amount collected by each salesman and the
 * total quantity sold for each product, and generates two CSV reports.</p>
 */
public class main {

    private static final String DATA_FOLDER = "data";
    private static final String SALESMEN_FILE = "salesmen.txt";
    private static final String PRODUCTS_FILE = "products.txt";
    private static final String SALES_FILE_PREFIX = "sales_";

    private static final String SALESMEN_REPORT = "salesmen_report.csv";
    private static final String PRODUCTS_REPORT = "products_report.csv";

    public static void main(String[] args) {
        try {
            Map<Long, Salesman> salesmen = readSalesmen();
            Map<Integer, Product> products = readProducts();

            processSalesFiles(salesmen, products);

            generateSalesmenReport(salesmen);
            generateProductsReport(products);

            System.out.println("Reportes generados exitosamente.");
        } catch (IOException | IllegalArgumentException e) {
            System.out.println("Error al procesar los archivos: " + e.getMessage());
        }
    }

    /**
     * Reads the information of all salesmen.
     *
     * @return map indexed by the salesman's identification number
     * @throws IOException if the file cannot be read
     */
    private static Map<Long, Salesman> readSalesmen() throws IOException {
        Map<Long, Salesman> salesmen = new HashMap<Long, Salesman>();

        File file = new File(DATA_FOLDER, SALESMEN_FILE);

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(";");

                if (data.length < 4) {
                    throw new IllegalArgumentException(
                            "Formato incorrecto en salesmen.txt: " + line);
                }

                String documentType = data[0].trim();
                long documentNumber = Long.parseLong(data[1].trim());
                String firstName = data[2].trim();
                String lastName = data[3].trim();

                Salesman salesman = new Salesman(
                        documentType,
                        documentNumber,
                        firstName,
                        lastName
                );

                salesmen.put(documentNumber, salesman);
            }
        }

        return salesmen;
    }

    /**
     * Reads all available products.
     *
     * @return map indexed by product ID
     * @throws IOException if the file cannot be read
     */
    private static Map<Integer, Product> readProducts() throws IOException {
        Map<Integer, Product> products = new HashMap<Integer, Product>();

        File file = new File(DATA_FOLDER, PRODUCTS_FILE);

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(";");

                if (data.length < 3) {
                    throw new IllegalArgumentException(
                            "Formato incorrecto en products.txt: " + line);
                }

                int id = Integer.parseInt(data[0].trim());
                String name = data[1].trim();
                long price = Long.parseLong(data[2].trim());

                if (price < 0) {
                    throw new IllegalArgumentException(
                            "El precio del producto no puede ser negativo: " + id);
                }

                products.put(id, new Product(id, name, price));
            }
        }

        return products;
    }

    /**
     * Finds every sales_*.txt file and processes its sales.
     *
     * @param salesmen map containing all salesmen
     * @param products map containing all products
     * @throws IOException if a file cannot be read
     */
    private static void processSalesFiles(
            Map<Long, Salesman> salesmen,
            Map<Integer, Product> products) throws IOException {

        File folder = new File(DATA_FOLDER);

        File[] files = folder.listFiles();

        if (files == null) {
            throw new IOException("No fue posible acceder a la carpeta data.");
        }

        for (File file : files) {
            if (!file.isFile()
                    || !file.getName().startsWith(SALES_FILE_PREFIX)
                    || !file.getName().endsWith(".txt")) {
                continue;
            }

            processSalesFile(file, salesmen, products);
        }
    }

    /**
     * Processes the sales contained in one sales file.
     *
     * @param file sales file
     * @param salesmen map containing all salesmen
     * @param products map containing all products
     * @throws IOException if the file cannot be read
     */
    private static void processSalesFile(
            File file,
            Map<Long, Salesman> salesmen,
            Map<Integer, Product> products) throws IOException {

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String firstLine = reader.readLine();

            if (firstLine == null || firstLine.trim().isEmpty()) {
                throw new IllegalArgumentException(
                        "El archivo está vacío: " + file.getName());
            }

            String[] salesmanData = firstLine.split(";");

            if (salesmanData.length < 2) {
                throw new IllegalArgumentException(
                        "Formato incorrecto en " + file.getName());
            }

            long salesmanId = Long.parseLong(salesmanData[1].trim());
            Salesman salesman = salesmen.get(salesmanId);

            if (salesman == null) {
                throw new IllegalArgumentException(
                        "El vendedor " + salesmanId
                                + " no existe en salesmen.txt.");
            }

            String line;

            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(";");

                if (data.length < 2) {
                    throw new IllegalArgumentException(
                            "Formato incorrecto en " + file.getName()
                                    + ": " + line);
                }

                int productId = Integer.parseInt(data[0].trim());
                int quantity = Integer.parseInt(data[1].trim());

                if (quantity <= 0) {
                    throw new IllegalArgumentException(
                            "La cantidad debe ser mayor que cero: " + line);
                }

                Product product = products.get(productId);

                if (product == null) {
                    throw new IllegalArgumentException(
                            "El producto " + productId
                                    + " no existe en products.txt.");
                }

                long saleValue = product.getPrice() * quantity;

                salesman.addRevenue(saleValue);
                product.addQuantitySold(quantity);
            }
        }
    }

    /**
     * Generates the salesman report ordered by total revenue, descending.
     *
     * @param salesmen map containing the processed salesmen
     * @throws IOException if the report cannot be created
     */
    private static void generateSalesmenReport(
            Map<Long, Salesman> salesmen) throws IOException {

        List<Salesman> salesmanList =
                new ArrayList<Salesman>(salesmen.values());

        Collections.sort(salesmanList, new Comparator<Salesman>() {
            @Override
            public int compare(Salesman first, Salesman second) {
                return Long.compare(
                        second.getTotalRevenue(),
                        first.getTotalRevenue()
                );
            }
        });

        File report = new File(DATA_FOLDER, SALESMEN_REPORT);

        try (BufferedWriter writer =
                     new BufferedWriter(new FileWriter(report))) {

            for (Salesman salesman : salesmanList) {
                writer.write(
                        salesman.getFirstName()
                                + " "
                                + salesman.getLastName()
                                + ";"
                                + salesman.getTotalRevenue()
                );
                writer.newLine();
            }
        }
    }

    /**
     * Generates the product report ordered by quantity sold, descending.
     *
     * <p>The requested output contains the product name and unit price,
     * separated by semicolons. The quantity is used for the ordering.</p>
     *
     * @param products map containing the processed products
     * @throws IOException if the report cannot be created
     */
    private static void generateProductsReport(
            Map<Integer, Product> products) throws IOException {

        List<Product> productList =
                new ArrayList<Product>(products.values());

        Collections.sort(productList, new Comparator<Product>() {
            @Override
            public int compare(Product first, Product second) {
                return Long.compare(
                        second.getQuantitySold(),
                        first.getQuantitySold()
                );
            }
        });

        File report = new File(DATA_FOLDER, PRODUCTS_REPORT);

        try (BufferedWriter writer =
                     new BufferedWriter(new FileWriter(report))) {

            for (Product product : productList) {
                if (product.getQuantitySold() > 0) {
                    writer.write(
                            product.getName()
                                    + ";"
                                    + product.getPrice()
                    );
                    writer.newLine();
                }
            }
        }
    }

    /**
     * Represents a salesman.
     */
    private static class Salesman {

        private final String documentType;
        private final long documentNumber;
        private final String firstName;
        private final String lastName;
        private long totalRevenue;

        Salesman(
                String documentType,
                long documentNumber,
                String firstName,
                String lastName) {

            this.documentType = documentType;
            this.documentNumber = documentNumber;
            this.firstName = firstName;
            this.lastName = lastName;
            this.totalRevenue = 0;
        }

        void addRevenue(long value) {
            totalRevenue += value;
        }

        String getFirstName() {
            return firstName;
        }

        String getLastName() {
            return lastName;
        }

        long getTotalRevenue() {
            return totalRevenue;
        }
    }

    /**
     * Represents a product.
     */
    private static class Product {

        private final int id;
        private final String name;
        private final long price;
        private long quantitySold;

        Product(int id, String name, long price) {
            this.id = id;
            this.name = name;
            this.price = price;
            this.quantitySold = 0;
        }

        void addQuantitySold(long quantity) {
            quantitySold += quantity;
        }

        String getName() {
            return name;
        }

        long getPrice() {
            return price;
        }

        long getQuantitySold() {
            return quantitySold;
        }
    }
}
